/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Clone a file or directory synchronously using native Copy-on-Write
 *
 * - macOS: Uses clonefile() which supports both files and directories
 * - Linux: Uses FICLONE ioctl which only supports files
 */
export declare function cloneSync(src: string, dest: string): void
/**
 * Clone a file or directory asynchronously using native Copy-on-Write
 *
 * - macOS: Uses clonefile() which supports both files and directories
 * - Linux: Uses FICLONE ioctl which only supports files
 */
export declare function cloneAsync(src: string, dest: string): Promise<void>
/** Clone a file or directory synchronously (alias for cloneSync for backward compatibility) */
export declare function clone(src: string, dest: string): void
/** Check if native clone operations are available */
export declare function isAvailable(): boolean
/**
 * Check if directory cloning is supported
 * - macOS clonefile: true (supports directories)
 * - Linux FICLONE: false (files only)
 */
export declare function supportsDirectory(): boolean
/**
 * Get the current platform
 * Returns "darwin" or "linux"
 */
export declare function getPlatform(): "darwin" | "linux"
