import { type FlagSpec, SUBCOMMANDS, GLOBAL_FLAGS } from "./completion-spec.ts";

const ALL_BRANCHES_CMD = "git for-each-ref --format='%(refname:short)' refs/heads 2>/dev/null";

const WORKTREE_BRANCHES_CMD =
  "git worktree list --porcelain 2>/dev/null | string match -rg '^branch refs/heads/(.+)'";

// fish single-quoted strings allow `\'` and `\\` escapes; nothing else needs escaping.
function escapeFishSingleQuoted(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

function flagToComplete(flag: FlagSpec, condition?: string): string {
  const parts = ["complete -c vibe"];
  if (condition) {
    parts.push(`-n '${condition}'`);
  }
  if (flag.short) {
    parts.push(`-s ${flag.short}`);
  }
  parts.push(`-l ${flag.long}`);
  if (flag.takesValue) {
    parts.push("-r");
  }
  if (flag.valueCandidates) {
    parts.push(`-xa '${flag.valueCandidates.join(" ")}'`);
  }
  parts.push(`-d '${escapeFishSingleQuoted(flag.description)}'`);
  return parts.join(" ");
}

export function generateFishCompletion(): string {
  const lines: string[] = [
    "# vibe fish completion — generated by `vibe shell-setup --shell fish --with-completion`",
    "complete -c vibe -f",
    "",
    "# Subcommands",
  ];

  for (const cmd of SUBCOMMANDS) {
    const desc = escapeFishSingleQuoted(cmd.description);
    lines.push(`complete -c vibe -n __fish_use_subcommand -a ${cmd.name} -d '${desc}'`);
  }

  lines.push("", "# Global flags");
  for (const flag of GLOBAL_FLAGS) {
    lines.push(flagToComplete(flag));
  }

  lines.push("", "# Dynamic positional completion");
  lines.push(
    `complete -c vibe -n '__fish_seen_subcommand_from start' -k -a "(${ALL_BRANCHES_CMD})"`,
  );
  lines.push(
    `complete -c vibe -n '__fish_seen_subcommand_from jump' -k -a "(${WORKTREE_BRANCHES_CMD})"`,
  );

  for (const cmd of SUBCOMMANDS) {
    const flags = cmd.flags;
    if (!flags?.length) continue;
    lines.push("", `# ${cmd.name} flags`);
    const condition = `__fish_seen_subcommand_from ${cmd.name}`;
    for (const flag of flags) {
      lines.push(flagToComplete(flag, condition));
    }
  }

  return lines.join("\n") + "\n";
}
