export interface FlagSpec {
  long: string;
  short?: string;
  description: string;
  takesValue?: boolean;
  valueCandidates?: readonly string[];
}

export interface CommandSpec {
  name: string;
  description: string;
  flags?: readonly FlagSpec[];
}

export const SUBCOMMANDS: readonly CommandSpec[] = [
  {
    name: "start",
    description: "Create a new worktree with the given branch",
    flags: [
      { long: "reuse", description: "Use existing branch instead of creating a new one" },
      { long: "base", description: "Base branch/commit for new branch", takesValue: true },
      { long: "track", description: "Set upstream tracking when using --base" },
      { long: "no-hooks", description: "Skip pre-start and post-start hooks" },
      { long: "no-copy", description: "Skip copying files and directories" },
      { long: "dry-run", short: "n", description: "Show what would be executed" },
      { long: "force", short: "f", description: "Skip confirmation prompts" },
    ],
  },
  {
    name: "scratch",
    description: "Create a worktree with an auto-generated scratch/<timestamp> branch",
    flags: [
      { long: "reuse", description: "Use existing branch instead of creating a new one" },
      { long: "base", description: "Base branch/commit for new branch", takesValue: true },
      { long: "track", description: "Set upstream tracking when using --base" },
      { long: "no-hooks", description: "Skip pre-start and post-start hooks" },
      { long: "no-copy", description: "Skip copying files and directories" },
      { long: "dry-run", short: "n", description: "Show what would be executed" },
    ],
  },
  { name: "jump", description: "Jump to an existing worktree by branch name" },
  {
    name: "rename",
    description: "Rename the current worktree's branch and directory",
    flags: [{ long: "dry-run", short: "n", description: "Show what would be executed" }],
  },
  {
    name: "clean",
    description: "Remove current worktree and return to main",
    flags: [
      { long: "force", short: "f", description: "Skip confirmation prompts" },
      { long: "delete-branch", description: "Delete the branch after removing the worktree" },
      { long: "keep-branch", description: "Keep the branch after removing the worktree" },
    ],
  },
  { name: "home", description: "Return to main worktree without removing current" },
  { name: "trust", description: "Trust .vibe.toml in current repository" },
  { name: "untrust", description: "Remove trust for .vibe.toml in current repository" },
  { name: "verify", description: "Verify trust status and hash history" },
  { name: "config", description: "Show current settings" },
  {
    name: "upgrade",
    description: "Check for updates and show upgrade instructions",
    flags: [{ long: "check", description: "Check for updates without upgrade instructions" }],
  },
  {
    name: "shell-setup",
    description: "Print shell wrapper function for eval",
    flags: [
      {
        long: "shell",
        description: "Specify shell type",
        takesValue: true,
        valueCandidates: ["bash", "zsh", "fish", "nushell", "powershell"],
      },
      { long: "with-completion", description: "Include fish autocompletion (fish only)" },
    ],
  },
];

export const GLOBAL_FLAGS: readonly FlagSpec[] = [
  { long: "help", short: "h", description: "Show help message" },
  { long: "version", short: "v", description: "Show version information" },
  { long: "verbose", short: "V", description: "Show detailed output" },
  { long: "quiet", short: "q", description: "Suppress non-essential output" },
];

const ALL_BRANCHES_CMD = "git for-each-ref --format='%(refname:short)' refs/heads 2>/dev/null";

const WORKTREE_BRANCHES_CMD =
  "git worktree list --porcelain 2>/dev/null | string match -rg '^branch refs/heads/(.+)'";

// fish single-quoted strings allow `\'` and `\\` escapes; nothing else needs escaping.
function escapeFishSingleQuoted(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

function flagToComplete(flag: FlagSpec, condition?: string): string {
  const parts = ["complete -c vibe"];
  if (condition) {
    parts.push(`-n '${condition}'`);
  }
  if (flag.short) {
    parts.push(`-s ${flag.short}`);
  }
  parts.push(`-l ${flag.long}`);
  if (flag.takesValue) {
    parts.push("-r");
  }
  if (flag.valueCandidates) {
    parts.push(`-xa '${flag.valueCandidates.join(" ")}'`);
  }
  parts.push(`-d '${escapeFishSingleQuoted(flag.description)}'`);
  return parts.join(" ");
}

export function generateFishCompletion(): string {
  const lines: string[] = [
    "# vibe fish completion — generated by `vibe shell-setup --shell fish --with-completion`",
    "complete -c vibe -f",
    "",
    "# Subcommands",
  ];

  for (const cmd of SUBCOMMANDS) {
    const desc = escapeFishSingleQuoted(cmd.description);
    lines.push(`complete -c vibe -n __fish_use_subcommand -a ${cmd.name} -d '${desc}'`);
  }

  lines.push("", "# Global flags");
  for (const flag of GLOBAL_FLAGS) {
    lines.push(flagToComplete(flag));
  }

  lines.push("", "# Dynamic positional completion");
  lines.push(
    `complete -c vibe -n '__fish_seen_subcommand_from start' -k -a "(${ALL_BRANCHES_CMD})"`,
  );
  lines.push(
    `complete -c vibe -n '__fish_seen_subcommand_from jump' -k -a "(${WORKTREE_BRANCHES_CMD})"`,
  );

  for (const cmd of SUBCOMMANDS) {
    const flags = cmd.flags;
    const hasFlags = flags !== undefined && flags.length > 0;
    if (!hasFlags) continue;
    lines.push("", `# ${cmd.name} flags`);
    const condition = `__fish_seen_subcommand_from ${cmd.name}`;
    for (const flag of flags) {
      lines.push(flagToComplete(flag, condition));
    }
  }

  return lines.join("\n") + "\n";
}
