import { SUBCOMMANDS, GLOBAL_FLAGS, type CommandSpec, type FlagSpec } from "./completion-spec.ts";

const ALL_BRANCHES_CMD = "git for-each-ref --format='%(refname:short)' refs/heads 2>/dev/null";

const WORKTREE_BRANCHES_CMD =
  "git worktree list --porcelain 2>/dev/null | " +
  "awk '/^branch refs\\/heads\\//{sub(/^branch refs\\/heads\\//, \"\"); print}'";

const BRANCH_POSITIONAL_SUBCOMMANDS = new Set(["start", "scratch"]);
const WORKTREE_BRANCH_POSITIONAL_SUBCOMMANDS = new Set(["jump"]);

// zsh single-quoted strings: only ' needs escaping, via close-escape-reopen.
function escapeZshSingleQuoted(value: string): string {
  return value.replace(/'/g, "'\\''");
}

// Inside `_arguments` `[description]` segments and `_describe` `display:description`
// list elements, `\`, `:`, `[`, and `]` are zsh metacharacters that must be escaped
// so future description edits cannot accidentally break the parser.
function escapeZshDescription(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/:/g, "\\:")
    .replace(/\[/g, "\\[")
    .replace(/\]/g, "\\]");
}

function zshFunctionName(subcommand: string): string {
  return `_vibe_${subcommand.replace(/-/g, "_")}`;
}

function buildFlagSpec(flag: FlagSpec): string {
  const desc = escapeZshSingleQuoted(escapeZshDescription(flag.description));
  const hasShort = flag.short !== undefined;

  if (flag.takesValue) {
    const action = flag.valueCandidates ? `(${flag.valueCandidates.join(" ")})` : "";
    const valueMessage = flag.long;
    if (hasShort) {
      return `'(-${flag.short} --${flag.long})'{-${flag.short},--${flag.long}}'=[${desc}]:${valueMessage}:${action}'`;
    }
    return `'--${flag.long}=[${desc}]:${valueMessage}:${action}'`;
  }

  if (hasShort) {
    return `'(-${flag.short} --${flag.long})'{-${flag.short},--${flag.long}}'[${desc}]'`;
  }
  return `'--${flag.long}[${desc}]'`;
}

function buildSubcommandHandler(cmd: CommandSpec): string {
  const fn = zshFunctionName(cmd.name);
  const lines: string[] = [`${fn}() {`];

  const flagSpecs = (cmd.flags ?? []).map(buildFlagSpec);

  const isAllBranchPositional = BRANCH_POSITIONAL_SUBCOMMANDS.has(cmd.name);
  const isWorktreeBranchPositional = WORKTREE_BRANCH_POSITIONAL_SUBCOMMANDS.has(cmd.name);

  let positionalAction: string | null = null;
  if (isAllBranchPositional) positionalAction = "'1: :_vibe_branches'";
  else if (isWorktreeBranchPositional) positionalAction = "'1: :_vibe_worktree_branches'";

  const hasNothingToComplete = flagSpecs.length === 0 && positionalAction === null;
  if (hasNothingToComplete) {
    lines.push("  _arguments");
    lines.push("}");
    return lines.join("\n");
  }

  const specs = [...flagSpecs];
  if (positionalAction !== null) specs.push(positionalAction);

  lines.push("  _arguments \\");
  specs.forEach((spec, i) => {
    const isLast = i === specs.length - 1;
    lines.push(isLast ? `    ${spec}` : `    ${spec} \\`);
  });
  lines.push("}");
  return lines.join("\n");
}

export function generateZshCompletion(): string {
  const out: string[] = [
    "#compdef vibe",
    "# vibe zsh completion — generated by `vibe shell-setup --shell zsh --with-completion`",
    "",
    "_vibe_commands() {",
    "  local -a commands",
    "  commands=(",
  ];

  for (const cmd of SUBCOMMANDS) {
    const desc = escapeZshSingleQuoted(escapeZshDescription(cmd.description));
    out.push(`    '${cmd.name}:${desc}'`);
  }

  out.push(
    "  )",
    "  _describe 'command' commands",
    "}",
    "",
    "_vibe_branches() {",
    "  local -a branches",
    `  branches=("\${(@f)$(${ALL_BRANCHES_CMD})}")`,
    "  compadd -a branches",
    "}",
    "",
    "_vibe_worktree_branches() {",
    "  local -a branches",
    `  branches=("\${(@f)$(${WORKTREE_BRANCHES_CMD})}")`,
    "  compadd -a branches",
    "}",
    "",
  );

  for (const cmd of SUBCOMMANDS) {
    out.push(buildSubcommandHandler(cmd), "");
  }

  out.push(
    "_vibe() {",
    '  local curcontext="$curcontext" state line',
    "  typeset -A opt_args",
    "",
    "  _arguments -C \\",
  );

  for (const flag of GLOBAL_FLAGS) {
    out.push(`    ${buildFlagSpec(flag)} \\`);
  }

  out.push(
    "    '1: :_vibe_commands' \\",
    "    '*::arg:->args'",
    "",
    "  case $state in",
    "    args)",
    "      case $line[1] in",
  );

  for (const cmd of SUBCOMMANDS) {
    out.push(`        ${cmd.name}) ${zshFunctionName(cmd.name)} ;;`);
  }

  // Guard `compdef` so the script is a no-op (not an error) when eval'd before
  // `autoload -Uz compinit && compinit`. Use `if/fi` rather than `&&` so the
  // script's overall exit status stays 0 when the guard is false — important
  // for users with `setopt err_exit`.
  out.push(
    "      esac",
    "      ;;",
    "  esac",
    "}",
    "",
    "if (( ${+functions[compdef]} )); then",
    "  compdef _vibe vibe",
    "fi",
    "",
  );

  return out.join("\n");
}
