import {
  SUBCOMMANDS,
  GLOBAL_FLAGS,
  type CommandSpec,
  type FlagSpec,
  type PositionalCompletion,
} from "./completion-spec.ts";

const ALL_BRANCHES_CMD = "git for-each-ref --format='%(refname:short)' refs/heads 2>/dev/null";

const WORKTREE_BRANCHES_CMD =
  "git worktree list --porcelain 2>/dev/null | " +
  "awk '/^branch refs\\/heads\\//{sub(/^branch refs\\/heads\\//, \"\"); print}'";

const POSITIONAL_ACTION: Record<PositionalCompletion, string> = {
  "all-branches": "'1: :_vibe_branches'",
  "worktree-branches": "'1: :_vibe_worktree_branches'",
};

// zsh single-quoted strings treat every character literally — even backslash —
// so the only way to embed a literal `'` is to close the quote, escape the `'`,
// then reopen: `'\''`.
function escapeZshSingleQuoted(value: string): string {
  return value.replace(/'/g, "'\\''");
}

// Inside `_arguments` `[description]` segments and `_describe` `display:description`
// list elements, `\`, `:`, `[`, and `]` are zsh metacharacters that must be escaped
// so future description edits cannot accidentally break the parser.
function escapeZshDescription(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/:/g, "\\:")
    .replace(/\[/g, "\\[")
    .replace(/\]/g, "\\]");
}

function zshFunctionName(subcommand: string): string {
  return `_vibe_${subcommand.replace(/-/g, "_")}`;
}

function buildFlagSpec(flag: FlagSpec): string {
  const desc = escapeZshSingleQuoted(escapeZshDescription(flag.description));
  const hasShort = flag.short !== undefined;

  if (flag.takesValue) {
    const action = flag.valueCandidates ? `(${flag.valueCandidates.join(" ")})` : "";
    // `metavarName` fills the `:message:` slot in `_arguments`, shown in the
    // completion UI as the placeholder for the value the user must type.
    const metavarName = flag.long;
    if (hasShort) {
      return `'(-${flag.short} --${flag.long})'{-${flag.short},--${flag.long}}'=[${desc}]:${metavarName}:${action}'`;
    }
    return `'--${flag.long}=[${desc}]:${metavarName}:${action}'`;
  }

  if (hasShort) {
    return `'(-${flag.short} --${flag.long})'{-${flag.short},--${flag.long}}'[${desc}]'`;
  }
  return `'--${flag.long}[${desc}]'`;
}

function buildSubcommandHandler(cmd: CommandSpec): string {
  const fn = zshFunctionName(cmd.name);
  const lines: string[] = [`${fn}() {`];

  const flagSpecs = (cmd.flags ?? []).map(buildFlagSpec);
  const positionalAction = cmd.positionalCompletion
    ? POSITIONAL_ACTION[cmd.positionalCompletion]
    : null;

  const isArgumentFree = flagSpecs.length === 0 && positionalAction === null;
  if (isArgumentFree) {
    lines.push("  _arguments");
    lines.push("}");
    return lines.join("\n");
  }

  const specs = [...flagSpecs];
  if (positionalAction !== null) specs.push(positionalAction);

  lines.push("  _arguments \\");
  for (const [i, spec] of specs.entries()) {
    const isLast = i === specs.length - 1;
    lines.push(isLast ? `    ${spec}` : `    ${spec} \\`);
  }
  lines.push("}");
  return lines.join("\n");
}

export function generateZshCompletion(): string {
  const lines: string[] = [
    "#compdef vibe",
    "# vibe zsh completion — generated by `vibe shell-setup --shell zsh --with-completion`",
    "",
    "_vibe_commands() {",
    "  local -a commands",
    "  commands=(",
  ];

  for (const cmd of SUBCOMMANDS) {
    const desc = escapeZshSingleQuoted(escapeZshDescription(cmd.description));
    lines.push(`    '${cmd.name}:${desc}'`);
  }

  lines.push(
    "  )",
    "  _describe 'command' commands",
    "}",
    "",
    "_vibe_branches() {",
    "  local -a branches",
    `  branches=("\${(@f)$(${ALL_BRANCHES_CMD})}")`,
    "  compadd -a branches",
    "}",
    "",
    "_vibe_worktree_branches() {",
    "  local -a branches",
    `  branches=("\${(@f)$(${WORKTREE_BRANCHES_CMD})}")`,
    "  compadd -a branches",
    "}",
    "",
  );

  for (const cmd of SUBCOMMANDS) {
    lines.push(buildSubcommandHandler(cmd), "");
  }

  lines.push(
    "_vibe() {",
    '  local curcontext="$curcontext" state line',
    "  typeset -A opt_args",
    "",
    "  _arguments -C \\",
  );

  for (const flag of GLOBAL_FLAGS) {
    lines.push(`    ${buildFlagSpec(flag)} \\`);
  }

  lines.push(
    "    '1: :_vibe_commands' \\",
    "    '*::arg:->args'",
    "",
    "  case $state in",
    "    args)",
    "      case $line[1] in",
  );

  for (const cmd of SUBCOMMANDS) {
    lines.push(`        ${cmd.name}) ${zshFunctionName(cmd.name)} ;;`);
  }

  // Guard `compdef` so the script is a no-op (not an error) when eval'd before
  // `autoload -Uz compinit && compinit`. Use `if/fi` rather than `&&` so the
  // script's overall exit status stays 0 when the guard is false — important
  // for users with `setopt err_exit`.
  lines.push(
    "      esac",
    "      ;;",
    "  esac",
    "}",
    "",
    "if (( ${+functions[compdef]} )); then",
    "  compdef _vibe vibe",
    "fi",
    "",
  );

  return lines.join("\n");
}
