//! fish shell completion generator.
//!
//! Ported from `packages/core/src/commands/fish-completion.ts`. The output must
//! be byte-for-byte identical to the TS generator (there is a snapshot test), so
//! the line assembly, escaping (`\` → `\\`, `'` → `\'`) and ordering mirror the
//! TS exactly.

use super::spec::{FlagSpec, PositionalCompletion, ALL_BRANCHES_CMD, GLOBAL_FLAGS, SUBCOMMANDS};

const WORKTREE_BRANCHES_CMD: &str =
    "git worktree list --porcelain 2>/dev/null | string match -rg '^branch refs/heads/(.+)'";

/// The dynamic shell command for a positional completion kind.
fn positional_command(kind: PositionalCompletion) -> &'static str {
    match kind {
        PositionalCompletion::AllBranches => ALL_BRANCHES_CMD,
        PositionalCompletion::WorktreeBranches => WORKTREE_BRANCHES_CMD,
    }
}

/// Escape a value for a fish single-quoted string: `\` → `\\`, then `'` → `\'`.
fn escape_fish_single_quoted(value: &str) -> String {
    value.replace('\\', "\\\\").replace('\'', "\\'")
}

/// Build a `complete -c vibe ...` line for one flag, optionally under a `-n`
/// condition. Mirrors the TS `flagToComplete` part ordering exactly.
fn flag_to_complete(flag: &FlagSpec, condition: Option<&str>) -> String {
    let mut parts = vec!["complete -c vibe".to_string()];
    if let Some(cond) = condition {
        parts.push(format!("-n '{cond}'"));
    }
    if let Some(short) = flag.short {
        parts.push(format!("-s {short}"));
    }
    parts.push(format!("-l {}", flag.long));
    if flag.takes_value {
        parts.push("-r".to_string());
    }
    if let Some(candidates) = flag.value_candidates {
        parts.push(format!("-xa '{}'", candidates.join(" ")));
    }
    parts.push(format!(
        "-d '{}'",
        escape_fish_single_quoted(flag.description)
    ));
    parts.join(" ")
}

/// Generate the fish completion script (trailing newline included).
pub fn generate_fish_completion() -> String {
    let mut lines: Vec<String> = vec![
        "# vibe fish completion — generated by `vibe shell-setup --shell fish --with-completion`"
            .to_string(),
        "complete -c vibe -f".to_string(),
        String::new(),
        "# Subcommands".to_string(),
    ];

    for cmd in SUBCOMMANDS {
        let desc = escape_fish_single_quoted(cmd.description);
        lines.push(format!(
            "complete -c vibe -n __fish_use_subcommand -a {} -d '{desc}'",
            cmd.name
        ));
    }

    lines.push(String::new());
    lines.push("# Global flags".to_string());
    for flag in GLOBAL_FLAGS {
        lines.push(flag_to_complete(flag, None));
    }

    lines.push(String::new());
    lines.push("# Dynamic positional completion".to_string());
    for cmd in SUBCOMMANDS {
        let Some(kind) = cmd.positional_completion else {
            continue;
        };
        let shell_cmd = positional_command(kind);
        lines.push(format!(
            "complete -c vibe -n '__fish_seen_subcommand_from {}' -k -a \"({shell_cmd})\"",
            cmd.name
        ));
    }

    for cmd in SUBCOMMANDS {
        if cmd.flags.is_empty() {
            continue;
        }
        lines.push(String::new());
        lines.push(format!("# {} flags", cmd.name));
        let condition = format!("__fish_seen_subcommand_from {}", cmd.name);
        for flag in cmd.flags {
            lines.push(flag_to_complete(flag, Some(&condition)));
        }
    }

    let mut out = lines.join("\n");
    out.push('\n');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The exact TS-generated output, captured byte-for-byte. This is the parity
    /// oracle — equivalent to the vitest snapshot test.
    const EXPECTED: &str = include_str!("snapshots/fish.snap");

    #[test]
    fn matches_typescript_snapshot_byte_for_byte() {
        assert_eq!(generate_fish_completion(), EXPECTED);
    }

    #[test]
    fn escapes_single_quote_in_rename_description() {
        // "worktree's" → fish escapes the apostrophe as \'.
        let script = generate_fish_completion();
        assert!(script.contains("Rename the current worktree\\'s branch and directory"));
    }
}
