//! zsh shell completion generator.
//!
//! Ported from `packages/core/src/commands/zsh-completion.ts`. Output must be
//! byte-for-byte identical to the TS generator (snapshot test), so the escaping
//! (`'` → `'\''`; description metachars `\ : [ ]`), the `_arguments` spec
//! assembly and the per-line backslash continuations match the TS exactly.

use super::spec::{
    CommandSpec, FlagSpec, PositionalCompletion, ALL_BRANCHES_CMD, GLOBAL_FLAGS, SUBCOMMANDS,
};

const WORKTREE_BRANCHES_CMD: &str = "git worktree list --porcelain 2>/dev/null | \
awk '/^branch refs\\/heads\\//{sub(/^branch refs\\/heads\\//, \"\"); print}'";

/// The `_arguments` positional action for a completion kind.
fn positional_action(kind: PositionalCompletion) -> &'static str {
    match kind {
        PositionalCompletion::AllBranches => "'1: :_vibe_branches'",
        PositionalCompletion::WorktreeBranches => "'1: :_vibe_worktree_branches'",
    }
}

/// Escape `'` for a zsh single-quoted string: close, escaped quote, reopen.
fn escape_zsh_single_quoted(value: &str) -> String {
    value.replace('\'', "'\\''")
}

/// Escape zsh `_arguments`/`_describe` description metacharacters.
fn escape_zsh_description(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace(':', "\\:")
        .replace('[', "\\[")
        .replace(']', "\\]")
}

/// `_vibe_<name>` with hyphens replaced by underscores.
fn zsh_function_name(subcommand: &str) -> String {
    format!("_vibe_{}", subcommand.replace('-', "_"))
}

/// Build one `_arguments` flag spec, mirroring the TS `buildFlagSpec`.
fn build_flag_spec(flag: &FlagSpec) -> String {
    let desc = escape_zsh_single_quoted(&escape_zsh_description(flag.description));

    if flag.takes_value {
        let action = match flag.value_candidates {
            Some(candidates) => format!("({})", candidates.join(" ")),
            None => String::new(),
        };
        let metavar = flag.long;
        if let Some(short) = flag.short {
            return format!(
                "'(-{short} --{long})'{{-{short},--{long}}}'=[{desc}]:{metavar}:{action}'",
                long = flag.long
            );
        }
        return format!("'--{long}=[{desc}]:{metavar}:{action}'", long = flag.long);
    }

    if let Some(short) = flag.short {
        return format!(
            "'(-{short} --{long})'{{-{short},--{long}}}'[{desc}]'",
            long = flag.long
        );
    }
    format!("'--{long}[{desc}]'", long = flag.long)
}

/// Build a `_vibe_<cmd>()` handler function, mirroring the TS
/// `buildSubcommandHandler`.
fn build_subcommand_handler(cmd: &CommandSpec) -> String {
    let fn_name = zsh_function_name(cmd.name);
    let mut lines = vec![format!("{fn_name}() {{")];

    let flag_specs: Vec<String> = cmd.flags.iter().map(build_flag_spec).collect();
    let positional = cmd.positional_completion.map(positional_action);

    let is_argument_free = flag_specs.is_empty() && positional.is_none();
    if is_argument_free {
        lines.push("  _arguments".to_string());
        lines.push("}".to_string());
        return lines.join("\n");
    }

    let mut specs = flag_specs;
    if let Some(action) = positional {
        specs.push(action.to_string());
    }

    lines.push("  _arguments \\".to_string());
    let last = specs.len() - 1;
    for (i, spec) in specs.iter().enumerate() {
        if i == last {
            lines.push(format!("    {spec}"));
        } else {
            lines.push(format!("    {spec} \\"));
        }
    }
    lines.push("}".to_string());
    lines.join("\n")
}

/// Generate the zsh completion script (trailing newline included).
pub fn generate_zsh_completion() -> String {
    let mut lines: Vec<String> = vec![
        "#compdef vibe".to_string(),
        "# vibe zsh completion — generated by `vibe shell-setup --shell zsh --with-completion`"
            .to_string(),
        String::new(),
        "_vibe_commands() {".to_string(),
        "  local -a commands".to_string(),
        "  commands=(".to_string(),
    ];

    for cmd in SUBCOMMANDS {
        let desc = escape_zsh_single_quoted(&escape_zsh_description(cmd.description));
        lines.push(format!("    '{}:{desc}'", cmd.name));
    }

    lines.extend([
        "  )".to_string(),
        "  _describe 'command' commands".to_string(),
        "}".to_string(),
        String::new(),
        "_vibe_branches() {".to_string(),
        "  local -a branches".to_string(),
        format!("  branches=(\"${{(@f)$({ALL_BRANCHES_CMD})}}\")"),
        "  compadd -a branches".to_string(),
        "}".to_string(),
        String::new(),
        "_vibe_worktree_branches() {".to_string(),
        "  local -a branches".to_string(),
        format!("  branches=(\"${{(@f)$({WORKTREE_BRANCHES_CMD})}}\")"),
        "  compadd -a branches".to_string(),
        "}".to_string(),
        String::new(),
    ]);

    for cmd in SUBCOMMANDS {
        lines.push(build_subcommand_handler(cmd));
        lines.push(String::new());
    }

    lines.extend([
        "_vibe() {".to_string(),
        "  local curcontext=\"$curcontext\" state line".to_string(),
        "  typeset -A opt_args".to_string(),
        String::new(),
        "  _arguments -C \\".to_string(),
    ]);

    for flag in GLOBAL_FLAGS {
        lines.push(format!("    {} \\", build_flag_spec(flag)));
    }

    lines.extend([
        "    '1: :_vibe_commands' \\".to_string(),
        "    '*::arg:->args'".to_string(),
        String::new(),
        "  case $state in".to_string(),
        "    args)".to_string(),
        "      case $line[1] in".to_string(),
    ]);

    for cmd in SUBCOMMANDS {
        lines.push(format!(
            "        {}) {} ;;",
            cmd.name,
            zsh_function_name(cmd.name)
        ));
    }

    lines.extend([
        "      esac".to_string(),
        "      ;;".to_string(),
        "  esac".to_string(),
        "}".to_string(),
        String::new(),
        "if (( ${+functions[compdef]} )); then".to_string(),
        "  compdef _vibe vibe".to_string(),
        "fi".to_string(),
        String::new(),
    ]);

    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The exact TS-generated output, captured byte-for-byte (the parity oracle).
    const EXPECTED: &str = include_str!("snapshots/zsh.snap");

    #[test]
    fn matches_typescript_snapshot_byte_for_byte() {
        assert_eq!(generate_zsh_completion(), EXPECTED);
    }

    #[test]
    fn escapes_single_quote_in_rename_description() {
        let script = generate_zsh_completion();
        assert!(script.contains("'rename:Rename the current worktree'\\''s branch and directory'"));
    }
}
