/**
 * Build script for vibe CLI
 * Generates version.ts with semver + commit hash + build metadata, then compiles the binary
 */

import { parseArgs } from "@std/cli/parse-args";

interface BuildMetadata {
  platform: string;
  arch: string;
  target: string;
  distribution: string;
  buildTime: string;
  buildEnv: string;
}

function parseTarget(target: string): { platform: string; arch: string } {
  const parts = target.split("-");
  const arch = parts[0]; // x86_64 or aarch64

  let platform = "unknown";
  if (target.includes("linux")) platform = "linux";
  else if (target.includes("darwin")) platform = "darwin";
  else if (target.includes("windows")) platform = "windows";

  return { platform, arch };
}

function detectCurrentTarget(): string {
  const os = Deno.build.os;
  const arch = Deno.build.arch;

  if (os === "linux") return `${arch}-unknown-linux-gnu`;
  if (os === "darwin") return `${arch}-apple-darwin`;
  if (os === "windows") return `${arch}-pc-windows-msvc`;

  throw new Error(`Unsupported platform: ${os}`);
}

async function getGitCommitHash(): Promise<string> {
  const command = new Deno.Command("git", {
    args: ["rev-parse", "--short", "HEAD"],
    stdout: "piped",
    stderr: "piped",
  });

  const { success, stdout } = await command.output();
  if (!success) {
    throw new Error("Failed to get git commit hash");
  }

  return new TextDecoder().decode(stdout).trim();
}

interface DenoJsonInfo {
  version: string;
  repository: string;
}

async function getDenoJsonInfo(): Promise<DenoJsonInfo> {
  const denoJson = JSON.parse(await Deno.readTextFile("deno.json"));
  return {
    version: denoJson.version,
    repository: denoJson.repository,
  };
}

async function generateBuildInfoFile(
  version: string,
  commitHash: string,
  repository: string,
  metadata: BuildMetadata,
): Promise<void> {
  const fullVersion = `${version}+${commitHash}`;
  const content = `// This file is auto-generated by scripts/build.ts
export interface BuildInfo {
  version: string;
  repository: string;
  platform: string;
  arch: string;
  target: string;
  distribution: string;
  buildTime: string;
  buildEnv: string;
}

export const BUILD_INFO: BuildInfo = {
  version: "${fullVersion}",
  repository: "${repository}",
  platform: "${metadata.platform}",
  arch: "${metadata.arch}",
  target: "${metadata.target}",
  distribution: "${metadata.distribution}",
  buildTime: "${metadata.buildTime}",
  buildEnv: "${metadata.buildEnv}",
};

// Backwards compatibility
export const VERSION = BUILD_INFO.version;
export const REPOSITORY_URL = BUILD_INFO.repository;
`;

  await Deno.writeTextFile("src/version.ts", content);
  console.log(`Generated src/version.ts with VERSION = "${fullVersion}"`);
  console.log(
    `  Platform: ${metadata.platform}-${metadata.arch} (${metadata.target})`,
  );
  console.log(`  Distribution: ${metadata.distribution}`);
  console.log(`  Build: ${metadata.buildTime} (${metadata.buildEnv})`);
}

interface CompileOptions {
  target?: string;
  output: string;
}

async function compile(options: CompileOptions): Promise<void> {
  const args = [
    "compile",
    "--allow-run",
    "--allow-read",
    "--allow-write",
    "--allow-env",
    "--allow-ffi",
  ];

  const hasTarget = options.target !== undefined;
  if (hasTarget) {
    args.push("--target", options.target);
  }

  args.push("--output", options.output);
  args.push("main.ts");

  const command = new Deno.Command("deno", {
    args,
    stdout: "inherit",
    stderr: "inherit",
  });

  const { success } = await command.output();
  if (!success) {
    throw new Error("Failed to compile");
  }
}

async function main(): Promise<void> {
  const args = parseArgs(Deno.args, {
    string: ["target", "distribution", "output"],
    boolean: ["generate-version-only"],
  });

  // Determine target
  let target: string;
  if (args.target) {
    target = args.target;
  } else {
    target = detectCurrentTarget();
    console.log(`No --target specified, auto-detected: ${target}`);
  }

  // Determine distribution
  const distribution = args.distribution ?? "dev";

  // Parse target to get platform and arch
  const { platform, arch } = parseTarget(target);

  // Determine build environment
  const buildEnv = Deno.env.get("CI") ? "github-actions" : "local";

  // Generate build time
  const buildTime = new Date().toISOString();

  const metadata: BuildMetadata = {
    platform,
    arch,
    target,
    distribution,
    buildTime,
    buildEnv,
  };

  const { version, repository } = await getDenoJsonInfo();
  const commitHash = await getGitCommitHash();

  await generateBuildInfoFile(version, commitHash, repository, metadata);

  if (args["generate-version-only"]) {
    return;
  }

  // Determine output filename
  const output = args.output ?? "vibe";

  // Pass target only if explicitly specified (cross-compilation)
  // If not specified, compile for current platform without --target flag
  const compileTarget = args.target ? target : undefined;

  await compile({ target: compileTarget, output });
  console.log("Build completed successfully");
}

main();
