/**
 * Build script for vibe CLI
 * Generates version.ts with semver + commit hash + build metadata, then compiles the binary
 *
 * Usage:
 *   bun run scripts/build.ts [options]
 *
 * Options:
 *   --target <target>        Cross-compile target (e.g., bun-darwin-arm64). Auto-detected if omitted.
 *   --output <name>          Output binary name (default: "vibe")
 *   --distribution <type>    Distribution type: dev, binary, deb (default: "dev")
 *   --generate-version-only  Only generate version.ts without compiling
 */

import { parseArgs, type ParseArgsConfig } from "node:util";
import { readFile, writeFile } from "node:fs/promises";
import { spawn } from "node:child_process";

interface BuildMetadata {
  platform: string;
  arch: string;
  target: string;
  distribution: string;
  buildTime: string;
  buildEnv: string;
}

/**
 * Bun target mapping
 * Maps legacy Deno target names to Bun target names
 */
const BUN_TARGETS: Record<string, string> = {
  "x86_64-unknown-linux-gnu": "bun-linux-x64",
  "aarch64-unknown-linux-gnu": "bun-linux-arm64",
  "x86_64-apple-darwin": "bun-darwin-x64",
  "aarch64-apple-darwin": "bun-darwin-arm64",
  "x86_64-pc-windows-msvc": "bun-windows-x64",
};

function parseTarget(target: string): { platform: string; arch: string } {
  // Handle both Deno-style and Bun-style target names
  if (target.startsWith("bun-")) {
    // bun-darwin-arm64 -> darwin, arm64
    const parts = target.split("-");
    return { platform: parts[1], arch: parts[2] };
  }

  // Deno-style: x86_64-apple-darwin
  const parts = target.split("-");
  const arch = parts[0]; // x86_64 or aarch64

  let platform = "unknown";
  if (target.includes("linux")) platform = "linux";
  else if (target.includes("darwin")) platform = "darwin";
  else if (target.includes("windows")) platform = "windows";

  return { platform, arch };
}

function detectCurrentTarget(): string {
  const platform = process.platform;
  const arch = process.arch;

  if (platform === "linux") {
    return arch === "arm64" ? "bun-linux-arm64" : "bun-linux-x64";
  }
  if (platform === "darwin") {
    return arch === "arm64" ? "bun-darwin-arm64" : "bun-darwin-x64";
  }
  if (platform === "win32") {
    return "bun-windows-x64";
  }

  throw new Error(`Unsupported platform: ${platform}`);
}

async function runCommand(
  cmd: string,
  args: string[],
  options?: { cwd?: string; inherit?: boolean },
): Promise<string> {
  return new Promise((resolve, reject) => {
    const proc = spawn(cmd, args, {
      cwd: options?.cwd,
      stdio: options?.inherit ? "inherit" : "pipe",
    });

    let stdout = "";
    let stderr = "";

    if (!options?.inherit) {
      proc.stdout?.on("data", (data) => {
        stdout += data.toString();
      });
      proc.stderr?.on("data", (data) => {
        stderr += data.toString();
      });
    }

    proc.on("close", (code) => {
      if (code !== 0) {
        reject(new Error(`${cmd} ${args.join(" ")} failed: ${stderr}`));
      } else {
        resolve(stdout.trim());
      }
    });

    proc.on("error", reject);
  });
}

async function getGitCommitHash(): Promise<string> {
  return runCommand("git", ["rev-parse", "--short", "HEAD"]);
}

interface PackageJsonInfo {
  version: string;
  repository: string;
}

async function getPackageJsonInfo(): Promise<PackageJsonInfo> {
  // Read version from deno.json (will be migrated to package.json later)
  const content = await readFile("deno.json", "utf-8");
  const json = JSON.parse(content);
  return {
    version: json.version,
    repository: json.repository,
  };
}

async function generateBuildInfoFile(
  version: string,
  commitHash: string,
  repository: string,
  metadata: BuildMetadata,
): Promise<void> {
  const fullVersion = `${version}+${commitHash}`;
  const content = `// This file is auto-generated by scripts/build.ts
export interface BuildInfo {
  version: string;
  repository: string;
  platform: string;
  arch: string;
  target: string;
  distribution: string;
  buildTime: string;
  buildEnv: string;
}

export const BUILD_INFO: BuildInfo = {
  version: "${fullVersion}",
  repository: "${repository}",
  platform: "${metadata.platform}",
  arch: "${metadata.arch}",
  target: "${metadata.target}",
  distribution: "${metadata.distribution}",
  buildTime: "${metadata.buildTime}",
  buildEnv: "${metadata.buildEnv}",
};

// Backwards compatibility
export const VERSION = BUILD_INFO.version;
export const REPOSITORY_URL = BUILD_INFO.repository;
`;

  await writeFile("packages/core/src/version.ts", content);
  console.log(`Generated packages/core/src/version.ts with VERSION = "${fullVersion}"`);
  console.log(`  Platform: ${metadata.platform}-${metadata.arch} (${metadata.target})`);
  console.log(`  Distribution: ${metadata.distribution}`);
  console.log(`  Build: ${metadata.buildTime} (${metadata.buildEnv})`);
}

interface CompileOptions {
  target?: string;
  output: string;
}

async function compile(options: CompileOptions): Promise<void> {
  const args = ["build", "--compile", "--minify"];

  if (options.target !== undefined) {
    args.push("--target", options.target);
  }

  args.push("--outfile", options.output);
  args.push("main.ts");

  await runCommand("bun", args, { inherit: true });
}

const parseArgsOptions: ParseArgsConfig["options"] = {
  target: { type: "string" },
  distribution: { type: "string" },
  output: { type: "string" },
  "generate-version-only": { type: "boolean" },
};

async function main(): Promise<void> {
  const { values } = parseArgs({
    args: process.argv.slice(2),
    options: parseArgsOptions,
    strict: true,
  });

  const args = values as {
    target?: string;
    distribution?: string;
    output?: string;
    "generate-version-only"?: boolean;
  };

  // Determine target
  let target: string;
  if (args.target) {
    // Convert Deno target to Bun target if needed
    target = BUN_TARGETS[args.target] ?? args.target;
  } else {
    target = detectCurrentTarget();
    console.log(`No --target specified, auto-detected: ${target}`);
  }

  // Determine distribution type for build metadata
  // - "dev": local development builds (default)
  // - "binary": standalone binary releases
  // - "deb": Debian package builds
  const distribution = args.distribution ?? "dev";

  // Parse target to get platform and arch
  const { platform, arch } = parseTarget(target);

  // Determine build environment
  const buildEnv = process.env.CI ? "github-actions" : "local";

  // Generate build time
  const buildTime = new Date().toISOString();

  const metadata: BuildMetadata = {
    platform,
    arch,
    target,
    distribution,
    buildTime,
    buildEnv,
  };

  const { version, repository } = await getPackageJsonInfo();
  const commitHash = await getGitCommitHash();

  await generateBuildInfoFile(version, commitHash, repository, metadata);

  if (args["generate-version-only"]) {
    return;
  }

  // Determine output filename
  const output = args.output ?? "vibe";

  // Pass target only if explicitly specified (cross-compilation)
  // If not specified, compile for current platform without --target flag
  const compileTarget = args.target ? target : undefined;

  await compile({ target: compileTarget, output });
  console.log("Build completed successfully");
}

main();
