/**
 * Build script for vibe CLI
 * Generates version.ts with semver + commit hash, then compiles the binary
 */

async function getGitCommitHash(): Promise<string> {
  const command = new Deno.Command("git", {
    args: ["rev-parse", "--short", "HEAD"],
    stdout: "piped",
    stderr: "piped",
  });

  const { success, stdout } = await command.output();
  if (!success) {
    throw new Error("Failed to get git commit hash");
  }

  return new TextDecoder().decode(stdout).trim();
}

interface DenoJsonInfo {
  version: string;
  repository: string;
}

async function getDenoJsonInfo(): Promise<DenoJsonInfo> {
  const denoJson = JSON.parse(await Deno.readTextFile("deno.json"));
  return {
    version: denoJson.version,
    repository: denoJson.repository,
  };
}

async function generateVersionFile(
  version: string,
  commitHash: string,
  repository: string,
): Promise<void> {
  const fullVersion = `${version}+${commitHash}`;
  const content = `// This file is auto-generated by scripts/build.ts
export const VERSION = "${fullVersion}";
export const REPOSITORY_URL = "${repository}";
`;

  await Deno.writeTextFile("src/version.ts", content);
  console.log(`Generated src/version.ts with VERSION = "${fullVersion}"`);
}

async function compile(): Promise<void> {
  const command = new Deno.Command("deno", {
    args: [
      "compile",
      "--allow-run",
      "--allow-read",
      "--allow-write",
      "--allow-env",
      "--output",
      "vibe",
      "main.ts",
    ],
    stdout: "inherit",
    stderr: "inherit",
  });

  const { success } = await command.output();
  if (!success) {
    throw new Error("Failed to compile");
  }
}

async function main(): Promise<void> {
  const { version, repository } = await getDenoJsonInfo();
  const commitHash = await getGitCommitHash();

  await generateVersionFile(version, commitHash, repository);
  await compile();

  console.log("Build completed successfully");
}

main();
