// This file is auto-generated by scripts/build.ts
export interface BuildInfo {
  version: string;
  repository: string;
  platform: string;
  arch: string;
  target: string;
  distribution: string;
  buildTime: string;
  buildEnv: string;
}

export const BUILD_INFO: BuildInfo = {
  version: "0.2.0+e6d5163",
  repository: "https://github.com/kexi/vibe",
  platform: "darwin",
  arch: "aarch64",
  target: "aarch64-apple-darwin",
  distribution: "dev",
  buildTime: "2025-12-28T10:23:12.605Z",
  buildEnv: "local",
};

// Backwards compatibility
export const VERSION = BUILD_INFO.version;
export const REPOSITORY_URL = BUILD_INFO.repository;
