name: Nix

on:
  push:
    branches: [main, develop]
    paths:
      - "flake.nix"
      - "flake.lock"
  pull_request:
    paths:
      - "flake.nix"
      - "flake.lock"

jobs:
  nix-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16

      - uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b # v8

      - name: Check flake
        run: nix flake check

      - name: Build
        run: nix build

      - name: Smoke test
        run: ./result/bin/vibe --help
